spring:
  shardingsphere:
    datasource:
      names: ds
      ds:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: org.mariadb.jdbc.Driver
        jdbc-url: jdbc:mariadb://localhost:3306/testdb
        username: root
        password: root
    rules:
      encrypt:
        encryptors:
          aes_encryptor:
            type: AES
            props:
              aes-key-value: ${AES_KEY}
              aes-key-length: 256
              iv-generator-class-name: org.apache.shardingsphere.encrypt.api.context.RandomIVGenerator
        tables:
          request_data:
            columns:
              roc_id:
                cipherColumn: roc_id_cipher
                assistedQueryColumn: roc_id_iv
                encryptorName: aes_encryptor
    props:
      sql-show: true

mybatis:
  type-aliases-package: com.example.infosync.model

server:
  port: 8080 