version: '3'
services:
  proxy:
    image: apache/shardingsphere-proxy:latest
    ports:
      - "3307:3307"
    volumes:
      - ./config:/opt/shardingsphere-proxy/conf
      - ./ext-lib:/opt/shardingsphere-proxy/ext-lib
    environment:
      - JVM_OPTS=-Djava.awt.headless=true
    depends_on:
      - zk

  zk:
    image: zookeeper
    ports:
      - "2181:2181"
